export enum FootballMatchStatusEnum {
    FINISHED = 5,
    NSY = 6,
    ABANDONED = 7,
    RESULT_ONLY = 8,
    NO_INFO_YET = 9,
    TO_FINISH = 11,
    CANCELLED = 12,
    FIRST_HALF = 13,
    HALF_TIME = 14,
    SECOND_HALF = 15,
    ET_FIRST_HALF = 16,
    ET_SECOND_HALF = 17,
    PENALITY = 18,
    FINISHED_AP = 20,
    FINISHED_AET = 21,
    POSTPONED = 22,
    FULL_TIME = 23,
    INTERRUPTED = 55,
    AWARDED = 123,
    DELAYED = 135
}